production:
  primary: &primary_production
    <<: *default
    database: shop202_production
    username: shop202
    password: <%= ENV.fetch("SHOP202_DATABASE_PASSWORD", "default_password") %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: shop202_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: shop202_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: shop202_production_cable
    migrations_paths: db/cable_migrate
